font_family Iosevka

# Layout settings
enabled_layouts tall, *

window_margin_width 5
window_border_width 2
single_window_margin_width 2



# Control the split window
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# Reload the setting
map ctrl+shift+r reload-config

allow_remote_control yes
listen_on unix:/tmp/kitty


# Set the background color
background #2e3440
background_opacity 0.85
